### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by toyahatariku** [toyahatariku/furima-33971#15]
こちら最終課題終了後報告を忘れたまま追加実装を進めてしまい、現状のGitHubのmasterの状態とデプロイサーバーもEC2に移行している状態になっております。
Heroku上のデータは最終課題終了時の状態ですが、
もし修正箇所があればHerokuにはどう対処すれば良いのかも教えて頂きたいです

フリマアプリのURL
https://furima-33971.herokuapp.com/

Basic認証のID | kuritayahato
パスワード | 123456

出品者用のメールアドレス | test@test.test
パスワード | aaaaaa1

購入者用のメールアドレス | test@test.testt
パスワード | aaaaaa1

**Comment by naru6117** [comment]
@toyahatariku さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

また、こちらでは挙動確認のみを行っております。
修正内容について疑問がある場合は、お手数ですが、通常通りメンターへご質問ください！

[修正依頼箇所]

- [ ] **issueに記載されたHerokuのURLにアクセスし、同じくissueに記載されたIDとパスワードを入力すると、最終課題アプリ（FURIMA）が表示されるようにしましょう！**
現所、ご記載いただいているIDとパスワードを記入しても、フリマの画面が表示されません。

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by toyahatariku** [comment]
挙動確認有難うございます。
修正箇所を確認したところ、issueへの記載のパスワードが間違っておりました。
下記が正しいURL及びパスワードです。大変失礼致しました、

フリマアプリのURL
https://furima-33971.herokuapp.com/

Basic認証のID | kuritahayato
パスワード | 123456

出品者用のメールアドレス | test@test.test
パスワード | aaaaaa1

購入者用のメールアドレス | test@test.testt
パスワード | aaaaaa1

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTMです✨**　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
